### ISSUE TITLE
Unable to convert datetime field from json to parquet 

### ISSUE THREAD

**Issue by nilpatel13** [pinterest/secor#1066]
we want to convert json message to parquet and we have a protobuf schema like 

syntax = "proto3";

import "google/protobuf/timestamp.proto";

message TestMsg{
  uint64 action_date = 1;
  string abc = 2 ;
  google.protobuf.Timestamp def = 3 ;

}

but when we run the programme we get error like this:

2019-11-14 12:55:07,733 [Thread-8] (com.pinterest.secor.consumer.Consumer:186) ERROR Thread failed
java.lang.RuntimeException: Failed to write message ParsedMessage{topic='Integrate-Test-ESP.info', kafkaPartition=5, offset=3303425, kafkaKey=1277316515541, payload={"action_date":"1573648581000017","abc":"123","def":"2019-11-13 18:01:36.869"}, timestamp=0, headers=[], mPartitions=[ad=2019-11-12]}
	at com.pinterest.secor.consumer.Consumer.consumeNextMessage(Consumer.java:255)
	at com.pinterest.secor.consumer.Consumer.run(Consumer.java:162)
Caused by: java.lang.RuntimeException: Error parsing protobuf message
	at com.pinterest.secor.util.ProtobufUtil.decodeProtobufMessage(ProtobufUtil.java:192)
	at com.pinterest.secor.util.ProtobufUtil.decodeProtobufOrJsonMessage(ProtobufUtil.java:217)
	at com.pinterest.secor.io.impl.ProtobufParquetFileReaderWriterFactory$ProtobufParquetFileWriter.write(ProtobufParquetFileReaderWriterFactory.java:122)
	at com.pinterest.secor.writer.MessageWriter.write(MessageWriter.java:105)
	at com.pinterest.secor.consumer.Consumer.consumeNextMessage(Consumer.java:244)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.pinterest.secor.util.ProtobufUtil.decodeProtobufMessage(ProtobufUtil.java:184)
	... 5 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
	at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:106)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.checkLastTagWas(CodedInputStream.java:635)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:834)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:548)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:521)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:634)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:308)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:833)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:548)
	at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:328)
	at com.pinterest.secor.common.Test$TestMsg.<init>(Test.java:118)
	at com.pinterest.secor.common.Test$TestMsg.<init>(Test.java:50)
	at com.pinterest.secor.common.Test$TestMsg$1.parsePartialFrom(Test.java:807)
	at com.pinterest.secor.common.Test$TestMsg$1.parsePartialFrom(Test.java:801)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at com.pinterest.secor.common.Test$TestMsg.parseFrom(Test.java:329)
	... 10 more

**Comment by holyshipt** [comment]
Did you correctly config following options? 
`message.timestamp.name=meta.timestamp`
`message.timestamp.name.separator=.`

**Comment by jimymodi** [comment]
We are also facing the same issue. @nilpatel13 did you find any workaround to it.
@holyshipt yes the config params are set correctly.

**Comment by jimymodi** [comment]
@nilpatel13 I figured this out. Actually it's related to protopuf and not to secor. In protopuf the timestamp type needs value in [RFC 3339](https://validator.w3.org/feed/docs/error/InvalidRFC3339Date.html). 
![image](https://user-images.githubusercontent.com/415224/71764113-93da7480-2f09-11ea-8c5f-ca762504075a.png)

So the value of def field in your example should be formatted as `2019-11-13T18:01:36.869Z` and not `2019-11-13 18:01:36.869`. Formatting your timestamp to RFC 3339, will solve this error of parsing.
