### ISSUE TITLE
Write message fails which using timestamp type in protocol buffer defination

### ISSUE THREAD

**Issue by jimymodi** [pinterest/secor#1133]
We are trying to write the messages in parquet format. The entire thing works successfully. But it starts failing if we use timestamp type in proto file definition like below :

```
import "google/protobuf/timestamp.proto";

...

    google.protobuf.Timestamp root_tstamp = 6;
```

Error we are getting is `Error parsing protobuf message`
Full stack 
```
java.lang.RuntimeException: Error parsing protobuf message
	at com.pinterest.secor.util.ProtobufUtil.decodeProtobufMessage(ProtobufUtil.java:175)
	at com.pinterest.secor.util.ProtobufUtil.decodeProtobufOrJsonMessage(ProtobufUtil.java:200)
	at com.pinterest.secor.io.impl.ProtobufParquetFileReaderWriterFactory$ProtobufParquetFileWriter.write(ProtobufParquetFileReaderWriterFactory.java:104)
	at com.pinterest.secor.writer.MessageWriter.write(MessageWriter.java:95)
	at com.pinterest.secor.consumer.Consumer.consumeNextMessage(Consumer.java:189)
	at com.pinterest.secor.consumer.Consumer.run(Consumer.java:106)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.pinterest.secor.util.ProtobufUtil.decodeProtobufMessage(ProtobufUtil.java:167)
	... 5 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
	at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:106)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.checkLastTagWas(CodedInputStream.java:633)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:832)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:548)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:521)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:634)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:308)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:831)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:548)
	at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:298)
	at com.shaadi.de.proto.campaignperformance.CampaignPerformance.<init>(CampaignPerformance.java:226)
	at com.shaadi.de.proto.campaignperformance.CampaignPerformance.<init>(CampaignPerformance.java:9)
	at com.shaadi.de.proto.campaignperformance.CampaignPerformance$1.parsePartialFrom(CampaignPerformance.java:3713)
	at com.shaadi.de.proto.campaignperformance.CampaignPerformance$1.parsePartialFrom(CampaignPerformance.java:3707)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at com.shaadi.de.proto.campaignperformance.CampaignPerformance.parseFrom(CampaignPerformance.java:1432)
	... 10 more
```

I verified the data and the value is as per the format of timestamp. What could be causing this.

The protoc version we are using is `libprotoc 3.11.2`. And also updated the  artifact version of `protobuf-java` and `protobuf-java-util` to the latest `3.11.1`

**Comment by jimymodi** [comment]
Duplicate of #1066
