### ISSUE TITLE
ArrayIndexOutOfBoundsException when kafka.new.consumer.topic.list is missing

### ISSUE THREAD

**Issue by sdomalap** [pinterest/secor#1231]
When we use secor.kafka.topic_filter instead of kafka.new.consumer.topic.list, and remove kafka.new.consumer.topic.list from the configuration.

2020-03-19 11:35:53,950 [Thread-4] (com.pinterest.secor.consumer.Consumer:186) ERROR Thread failed
java.lang.RuntimeException: Failed to initialize the consumer
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:154)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at com.pinterest.secor.reader.SecorKafkaMessageIterator.subscribe(SecorKafkaMessageIterator.java:153)
        at com.pinterest.secor.consumer.Consumer.init(Consumer.java:105)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:151)

**Comment by sdomalap** [comment]
submitted a [PR](https://github.com/pinterest/secor/pull/1232)

**Comment by HenryCaiHaiying** [comment]
Thanks for the fix, merged in.
