### ISSUE TITLE
unable to find valid certification path to requested target : How to disable SSL in secor for S3 uplaod

### ISSUE THREAD

**Issue by ksingh7** [pinterest/secor#1409]
Hi @HenryCaiHaiying 

I am finally able to test sector against AWS S3 and it is able to move kafak messages to S3 buckets. 

Next i am trying to test sector against Ceph S3 ( which is S3 compliant object storage ), the S3 endpoint that i have for Ceph are not HTTPS ( AWS SDK by default uses SSL, but Hadoop s3a can toggle that to true / false using this parameter ``fs.s3a.connection.ssl.enabled`` . Details [here](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/core-default.html)

In secor how can i turn off SSL such that the S3Uploader should not try to reach https Ceph S3 endpoint. I can see that you have closed the issue    #580  , can you please share the solution how to turn it off for non AWS S3 storage systems like Ceph S3 / others.

Thanks 

```
2020-06-24 12:19:40,343 [Thread-3] (com.pinterest.secor.uploader.Uploader) INFO  uploading topic india partition 0
2020-06-24 12:19:40,344 [Thread-3] (com.pinterest.secor.common.FileRegistry) INFO  Deleting writer for path /mnt/secor_data/message_logs/partition/1_12/india/offset=0/1_0_00000000000000000005
2020-06-24 12:19:40,347 [Thread-3] (com.pinterest.secor.io.impl.SequenceFileReaderWriterFactory) INFO  Closing sequence file writer: /mnt/secor_data/message_logs/partition/1_12/india/offset=0/1_0_00000000000000000005
2020-06-24 12:19:40,363 [Thread-3] (com.pinterest.secor.uploader.S3UploadManager) INFO  uploading file /mnt/secor_data/message_logs/partition/1_12/india/offset=0/1_0_00000000000000000005 to s3://my-kafka-backups-ks/raw_logs/india/offset=0/1_0_00000000000000000005 with no encryption
2020-06-24 12:19:40,868 [s3-transfer-manager-worker-1] (com.amazonaws.http.apache.utils.ApacheUtils) WARN  NoSuchMethodException was thrown when disabling normalizeUri. This indicates you are using an old version (< 4.5.8) of Apache http client. It is recommended to use http client version >= 4.5.9 to avoid the breaking change introduced in apache client 4.5.7 and the latency in exception handling. See https://github.com/aws/aws-sdk-java/issues/1919 for more information
2020-06-24 12:19:42,590 [Thread-3] (com.pinterest.secor.consumer.Consumer) ERROR Thread failed
java.lang.RuntimeException: Failed to apply upload policy
	at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:197)
	at com.pinterest.secor.consumer.Consumer.run(Consumer.java:178)
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1207)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1153)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5062)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5008)
	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:394)
	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:5950)
	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1812)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1772)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:168)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:148)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:115)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:45)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)

```

**Comment by HenryCaiHaiying** [comment]
@ksingh7 Is this issue resolved?
