### ISSUE TITLE
PartitionFinalizer failing for custom MessageParser

### ISSUE THREAD

**Issue by dclim** [pinterest/secor#146]
I have a message parser that generates partitions in S3 of the form "'y'=yyyy/'m'=MM/'d'=dd/'H'=HH". When I run the partition finalizer I get this error:

2015-11-18 23:21:42,824 [main](com.pinterest.secor.main.PartitionFinalizerMain:47) ERROR Partition finalizer failed
java.lang.AssertionError: wrong partition format: y=2015/m=11/d=18
    at com.pinterest.secor.parser.PartitionFinalizer.finalizePartitionsUpTo(PartitionFinalizer.java:143)
    at com.pinterest.secor.parser.PartitionFinalizer.finalizePartitions(PartitionFinalizer.java:190)
    at com.pinterest.secor.main.PartitionFinalizerMain.main(PartitionFinalizerMain.java:45)

I understand if having the '=' sign might cause a conflict when storing in Hive, but since I don't use Hive, it would be nice if this didn't fail.

**Comment by HenryCaiHaiying** [comment]
In this case, can you make a small code change in
PartitionFinalizer.java:143, move the hivePrefix check earlier so you can
skip this partition string parsing if your hivePrefix is not set?
