### ISSUE TITLE
Have trouble running run_tests.sh

### ISSUE THREAD

**Issue by kchew534** [pinterest/secor#154]
Hi,

I know this has been reported before. Yes I read the run_tests header but I am kind of confuse on what are the "Hadoop native libs" refer to? Those in lib/native (The share libraries) or something else? I am running this on mac os Yosemite and my thrift version is 0.9.3

---

scripts/run_tests.sh: line 55: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]

---

Running tests for Message Type: 0 and  ReaderWriter:com.pinterest.secor.io.impl.SequenceFileReaderWriterFactory using filesystem: s3n

---

running post_and_verify_test
running pkill -f 'com.pinterest.secor.main.ConsumerMain' || true
running pkill -f 'kafka.Kafka' || true
running pkill -f 'org.apache.zookeeper.server.quorum.QuorumPeerMain' || true
running rm -r -f /tmp/secor_dev
running s3cmd del --recursive s3://test-bucket/secor_dev
scripts/run_tests.sh: line 77: s3cmd: command not found
running s3cmd ls -r s3://test-bucket/secor_dev
scripts/run_tests.sh: line 77: s3cmd: command not found
running mkdir -p /tmp/secor_dev/logs
running scripts/run_kafka_class.sh         org.apache.zookeeper.server.quorum.QuorumPeerMain scripts/../zookeeper.test.properties >         /tmp/secor_dev/logs/zookeeper.log 2>&1 &
running scripts/run_kafka_class.sh kafka.Kafka scripts/../kafka.test.properties >         /tmp/secor_dev/logs/kafka_server.log 2>&1 &
running scripts/run_kafka_class.sh kafka.admin.TopicCommand --create --zookeeper         localhost:2181 --replication-factor 1 --partitions 2 --topic test >         /tmp/secor_dev/logs/create_topic.log 2>&1
running /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home//bin/java -server -ea -Dlog4j.configuration=log4j.dev.properties         -Dconfig=secor.test.backup.properties -Dsecor.s3.filesystem=s3n -Dsecor.file.reader.writer.factory=com.pinterest.secor.io.impl.SequenceFileReaderWriterFactory -cp _:lib/_         com.pinterest.secor.main.ConsumerMain > /tmp/secor_dev/logs/secor_backup.log 2>&1 &
running /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home//bin/java -server -ea -Dlog4j.configuration=log4j.dev.properties         -Dconfig=secor.test.backup.properties -cp _:lib/_         com.pinterest.secor.main.TestLogMessageProducerMain -t test -m 100 -p 1 -type 0 -timeshift 0 >         /tmp/secor_dev/logs/test_log_message_producer.log 2>&1
Waiting 40 sec for Secor to upload logs to s3
Verifying 100 0
running /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home//bin/java -server -ea -Dlog4j.configuration=log4j.dev.properties           -Dconfig=secor.test.backup.properties -Dsecor.s3.filesystem=s3n -Dsecor.file.reader.writer.factory=com.pinterest.secor.io.impl.SequenceFileReaderWriterFactory -cp _:lib/_           com.pinterest.secor.main.LogFileVerifierMain -t test -m 100 -q >           /tmp/secor_dev/logs/log_verifier_backup.log 2>&1
\e[1;41;97mVerification FAILED\e[0m
See log /tmp/secor_dev/logs/log_verifier_backup.log for more details
2015-12-11 12:52:33,216 [main](org.apache.hadoop.util.NativeCodeLoader:62) WARN  Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-12-11 12:52:34,439 [main](com.pinterest.secor.main.LogFileVerifierMain:99) ERROR Log file verifier failed
org.apache.hadoop.security.AccessControlException: Permission denied: s3n://test-bucket/secor_dev/backup/test
    at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.processException(Jets3tNativeFileSystemStore.java:449)
    at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.processException(Jets3tNativeFileSystemStore.java:427)
    at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.handleException(Jets3tNativeFileSystemStore.java:411)
    at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.retrieveMetadata(Jets3tNativeFileSystemStore.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
    at org.apache.hadoop.fs.s3native.$Proxy4.retrieveMetadata(Unknown Source)
    at org.apache.hadoop.fs.s3native.NativeS3FileSystem.listStatus(NativeS3FileSystem.java:526)
    at com.pinterest.secor.util.FileUtil.list(FileUtil.java:102)
    at com.pinterest.secor.util.FileUtil.listRecursively(FileUtil.java:119)
    at com.pinterest.secor.tools.LogFileVerifier.populateTopicPartitionToOffsetToFiles(LogFileVerifier.java:58)
    at com.pinterest.secor.tools.LogFileVerifier.verifyCounts(LogFileVerifier.java:116)
    at com.pinterest.secor.main.LogFileVerifierMain.main(LogFileVerifierMain.java:93)
Caused by: org.jets3t.service.impl.rest.HttpException: 403 Forbidden
    at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:425)
    at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:279)
    at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRestHead(RestStorageService.java:1052)
    at org.jets3t.service.impl.rest.httpclient.RestStorageService.getObjectImpl(RestStorageService.java:2264)
    at org.jets3t.service.impl.rest.httpclient.RestStorageService.getObjectDetailsImpl(RestStorageService.java:2193)
    at org.jets3t.service.StorageService.getObjectDetails(StorageService.java:1120)
    at org.jets3t.service.StorageService.getObjectDetails(StorageService.java:575)
    at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.retrieveMetadata(Jets3tNativeFileSystemStore.java:174)
    ... 13 more
See log /tmp/secor_dev/logs/secor_backup.log for more details
<snaporama>
2015-12-11 12:51:52,714 [Thread-0](kafka.utils.Logging$class:68) INFO  Property serializer.class is overridden to kafka.serializer.DefaultEncoder
Exception in thread "Thread-0" java.lang.RuntimeException: Undefined message encoding type: 0
    at com.pinterest.secor.tools.TestLogMessageProducer.run(TestLogMessageProducer.java:76)

---

TIA

Kim

**Comment by HenryCaiHaiying** [comment]
Those warnings refers to hadoop native libraries (e.g. libhadoop.so) is not
found in LD_LIBRARY_PATH or -Djava.library.path

Those libraries are usually used for compressions such as native gzip or
snappy.  We didn't package those libraries since there is no standard way
of doing this in pom.xml, and some encoding libraries needs special
licenses.

If you want the performance of those native libraries, you can copy them
from your hadoop installation (usually in lib/native) and set
LD_LIBRARY_PATH to pointing to those libraries.

**Comment by kchew534** [comment]
Thanks Henry. And I believe I have to install s3cmd and fakes3 as well, correct?

**Comment by HenryCaiHaiying** [comment]
I haven't run those integration tests manually in my laptop for a while
since travis-ci did this for us.  I think you probably need to install
s3cmd and fakes3.
