### ISSUE TITLE
How could I parse created_at field in Twitter's stream

### ISSUE THREAD

**Issue by Bongsakorn** [pinterest/secor#158]
I use JSON date parser but in Twitter's streams haven't timestamp. I got the error like this

```
java.lang.NumberFormatException: For input string: "Mon Dec 14 16:28:09 +0000 2015"
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
    at java.lang.Double.valueOf(Double.java:504)
    at com.pinterest.secor.parser.JsonMessageParser.extractTimestampMillis(JsonMessageParser.java:39)
    at com.pinterest.secor.parser.TimestampedMessageParser.extractPartitions(TimestampedMessageParser.java:104)
    at com.pinterest.secor.parser.MessageParser.parse(MessageParser.java:40)
    at com.pinterest.secor.consumer.Consumer.consumeNextMessage(Consumer.java:139)
    at com.pinterest.secor.consumer.Consumer.run(Consumer.java:93)
```

Could you please give me any suggestion?

**Comment by HenryCaiHaiying** [comment]
jsonMessageFormat is not configured to parse that date format.  Take a look
at DateMessageParser where you can specify your own input pattern in
message.timestamp.input.pattern

**Comment by Bongsakorn** [comment]
I set like this, but still the same. not working.

message.timestamp.input.pattern=^\w+ (\w+) (\d+) ([\d:]+) \+0000 (\d+)$

**Comment by HenryCaiHaiying** [comment]
You can either set a breakpoint in that code or use a small test program to
try to see whether regex pattern can match your message header.
