### ISSUE TITLE
SimpleDateFormat threading issue throws ArrayIndexOutOfBoundsException in TimestampedMessageParser

### ISSUE THREAD

**Issue by foovungle** [pinterest/secor#166]
Hi all,

I think there's a problem with using SimpleDateFormat in the TimestampedMessageParser on java 1.8.0:

    $ java -version
    java version "1.8.0_20"
    Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
    Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

The error is:

    java.lang.ArrayIndexOutOfBoundsException: 13
    at sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(BaseCalendar.java:453)
    at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2397)
    at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2312)
    at java.util.Calendar.complete(Calendar.java:2236)
    at java.util.Calendar.get(Calendar.java:1826)
    at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1119)
    at java.text.SimpleDateFormat.format(SimpleDateFormat.java:966)
    at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
    at java.text.DateFormat.format(DateFormat.java:345)
    at com.pinterest.secor.parser.TimestampedMessageParser.generatePartitions(TimestampedMessageParser.java:78)
    at com.pinterest.secor.parser.TimestampedMessageParser.extractPartitions(TimestampedMessageParser.java:99)
    at com.pinterest.secor.parser.MessageParser.parse(MessageParser.java:40)
    at com.pinterest.secor.consumer.Consumer.consumeNextMessage(Consumer.java:139)
    at com.pinterest.secor.consumer.Consumer.run(Consumer.java:93)

The relevant code at TimestampedMessageParser.java:78 is:

        String dt = "dt=" + mDtFormatter.format(date);

This line will probably be a problem as well:

        String hr = "hr=" + mHrFormatter.format(date);

For the first cut, I'm going to try to `synchronize` on `mDtFormatter`. But supposedly, it's not as fast as using a `ThreadLocal` variable.

What's the best way of fixing this?

Thanks

**Comment by foovungle** [comment]
Never mind. Just found this:
https://github.com/pinterest/secor/commit/2ab3f1646355c7ab95bef4d94ca19c61645c87f3
