### ISSUE TITLE
"not a gzip file" if you set `secor.file.extensions` to `.gz`

### ISSUE THREAD

**Issue by Roguelazer** [pinterest/secor#201]
I'm trying to use Secor to write delimited text files, compressed to gzip. Here's the relevant snippet of my configuration:

```
# To set a custom file extension set this to a valid file suffix, such as
# '.gz', '.part', etc.
secor.file.extension=.gz

# The secor file reader/writer used to read/write the data, by default we write sequence files
secor.file.reader.writer.factory=com.pinterest.secor.io.impl.DelimitedTextFileReaderWriterFactory

# To enable compression, set this to a valid compression codec implementing
# org.apache.hadoop.io.compress.CompressionCodec interface, such as
# 'org.apache.hadoop.io.compress.GzipCodec'.
secor.compression.codec=org.apache.hadoop.io.compress.GzipCodec
```

Note that I set `secor.file.extension` to `.gz`, as the comment in the stock configuration file suggests to.

And here's what happens any time I try to run secor:

```
2016-04-19 00:14:35,863 [Thread-5] (org.apache.hadoop.io.compress.CodecPool:181) INFO  Got brand-new decompressor [.gz]
2016-04-19 00:14:35,867 [Thread-5] (com.pinterest.secor.main.ConsumerMain$1:65) ERROR Thread Thread[Thread-5,5,main] failed
java.lang.RuntimeException: Failed to apply upload policy
    at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:115)
    at com.pinterest.secor.consumer.Consumer.run(Consumer.java:105)
Caused by: java.io.IOException: not a gzip file
    at org.apache.hadoop.io.compress.zlib.BuiltInGzipDecompressor.processBasicHeader(BuiltInGzipDecompressor.java:496)
    at org.apache.hadoop.io.compress.zlib.BuiltInGzipDecompressor.executeHeaderState(BuiltInGzipDecompressor.java:257)
    at org.apache.hadoop.io.compress.zlib.BuiltInGzipDecompressor.decompress(BuiltInGzipDecompressor.java:186)
    at org.apache.hadoop.io.compress.DecompressorStream.decompress(DecompressorStream.java:91)
    at org.apache.hadoop.io.compress.DecompressorStream.read(DecompressorStream.java:85)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
    at com.pinterest.secor.io.impl.DelimitedTextFileReaderWriterFactory$DelimitedTextFileReader.next(DelimitedTextFileReaderWriterFactory.java:80)
    at com.pinterest.secor.uploader.Uploader.trim(Uploader.java:137)
    at com.pinterest.secor.uploader.Uploader.trimFiles(Uploader.java:170)
    at com.pinterest.secor.uploader.Uploader.checkTopicPartition(Uploader.java:199)
    at com.pinterest.secor.uploader.Uploader.applyPolicy(Uploader.java:207)
    at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:113)
    ... 1 more
```

The error goes away if I set the `secor.file.extension` option to empty-string, and the files on S3 seem to still have `.gz` in them, so this is probably a documentation issue more than anything...

Incidentally, it would be super-cool if the file being uploaded were listed anywhere in that log message.

**Comment by HenryCaiHaiying** [comment]
Take a look at this PR, might fix your problem.

https://github.com/pinterest/secor/pull/198
