### ISSUE TITLE
Error : Failed to Apply Upload Policy

### ISSUE THREAD

**Issue by vthakre** [pinterest/secor#210]
I have secor deployed on an EC2 instance and it runs fine.
When I start another secor (EC2) instance, I get following exception

java.lang.RuntimeException: Failed to apply upload policy
    at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:115)
    at com.pinterest.secor.consumer.Consumer.run(Consumer.java:105)
Caused by: com.amazonaws.AmazonClientException: Unable to complete multi-part upload. Individual part upload failed : Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. (Service: Amazon S3; Status Code: 400; Error Code: RequestTimeout; Request ID: 8E4924EB9F46FDAA)

It happens when I start 2 secor instances at the same time.
Here are my secor properties: 
-secor.kafka.topic_filter=.*
-secor.max.file.size.bytes=500000
-secor.max.file.age.seconds=60
-secor.max.message.size.bytes=1000000
-secor.messages.per.second=1000000
-kafka.fetch.message.max.bytes=3000000
-secor.message.parser.class=(date-based parser)
-secor.consumer.threads=33

It runs for about 6 minutes before failing

Start one secor instance then start another one w/same configs.
Second secor instance fails w/same message

-Unable to complete multi-part upload. Individual part upload failed : Failed to open file /data/secor/2146_65/sixty-15/d_20160502-2310/1_30_00000000000000669199

I am using custom Message Parser to partition/group the data based on 10 minute window

**Comment by cscheffler** [comment]
I also get this, when uploading to S3.

Full stack trace below, but the basic behaviour is that secor runs for 15 minutes (which is the configured `secor.max.file.age.seconds` value) and then fails with a `SocketException`. Some files do get uploaded to S3, so this might be a transient network connectivity issue.

Running the backup (not partition) secor process on build secor-0.21.

Stack trace:
```
May 23, 2016 11:52:53 AM com.twitter.common.zookeeper.DistributedLockImpl unlock
INFO: Cleaning up this locks ephemeral node.
May 23, 2016 11:52:53 AM com.twitter.common.zookeeper.DistributedLockImpl cleanup
INFO: Cleaning up!
2016-05-23 11:52:53,342 [Thread-7] (com.pinterest.secor.main.ConsumerMain$1:65) ERROR Thread Thread[Thread-7,5,main] failed
java.lang.RuntimeException: Failed to apply upload policy
        at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:116)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:106)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.net.SocketException: Connection reset
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:188)
        at com.pinterest.secor.uploader.FutureHandle.get(FutureHandle.java:34)
        at com.pinterest.secor.uploader.Uploader.uploadFiles(Uploader.java:104)
        at com.pinterest.secor.uploader.Uploader.checkTopicPartition(Uploader.java:195)
        at com.pinterest.secor.uploader.Uploader.applyPolicy(Uploader.java:227)
        at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:114)
        ... 1 more
Caused by: java.lang.RuntimeException: java.net.SocketException: Connection reset
        at com.pinterest.secor.uploader.HadoopS3UploadManager$1.run(HadoopS3UploadManager.java:68)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
        at sun.security.ssl.InputRecord.read(InputRecord.java:480)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:934)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:891)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
        at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273)
        at org.apache.http.impl.conn.LoggingSessionInputBuffer.readLine(LoggingSessionInputBuffer.java:116)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
        at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
        at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
        at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:223)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
        at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:328)
        at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:279)
        at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRestPut(RestStorageService.java:1157)
        at org.jets3t.service.impl.rest.httpclient.RestStorageService.createObjectImpl(RestStorageService.java:1968)
        at org.jets3t.service.impl.rest.httpclient.RestStorageService.putObjectWithRequestEntityImpl(RestStorageService.java:1889)
        at org.jets3t.service.impl.rest.httpclient.RestStorageService.putObjectImpl(RestStorageService.java:1881)
        at org.jets3t.service.StorageService.putObject(StorageService.java:840)
        at org.jets3t.service.S3Service.putObject(S3Service.java:2212)
        at org.jets3t.service.S3Service.putObject(S3Service.java:2356)
        at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.storeFile(Jets3tNativeFileSystemStore.java:122)
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at org.apache.hadoop.fs.s3native.$Proxy5.storeFile(Unknown Source)
        at org.apache.hadoop.fs.s3native.NativeS3FileSystem$NativeS3FsOutputStream.close(NativeS3FileSystem.java:280)
        at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
        at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:61)
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:119)
        at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:366)
        at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:338)
        at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1965)
        at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1933)
        at org.apache.hadoop.fs.FileSystem.moveFromLocalFile(FileSystem.java:1920)
        at com.pinterest.secor.util.FileUtil.moveToCloud(FileUtil.java:206)
        at com.pinterest.secor.uploader.HadoopS3UploadManager$1.run(HadoopS3UploadManager.java:66)
        ... 5 more
```

**Comment by freakynit** [comment]
Im getting this exception too when uploading to GS. After around 15 minutes this error pops-up. Here's attached stacktrace:
```
2017-01-02 10:46:17,036 [Thread-10] (com.pinterest.secor.main.ConsumerMain$1:82) ERROR Thread Thread[Thread-10,5,main] failed
java.lang.RuntimeException: Failed to apply upload policy
	at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:116)
	at com.pinterest.secor.consumer.Consumer.run(Consumer.java:106)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: insufficient data written
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.pinterest.secor.uploader.FutureHandle.get(FutureHandle.java:34)
	at com.pinterest.secor.uploader.Uploader.uploadFiles(Uploader.java:108)
	at com.pinterest.secor.uploader.Uploader.checkTopicPartition(Uploader.java:220)
	at com.pinterest.secor.uploader.Uploader.applyPolicy(Uploader.java:252)
	at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:114)
	... 1 more
Caused by: java.lang.RuntimeException: java.io.IOException: insufficient data written
	at com.pinterest.secor.uploader.GsUploadManager$1.run(GsUploadManager.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: insufficient data written
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(HttpURLConnection.java:3500)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:81)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
	at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequestWithoutGZip(MediaHttpUploader.java:545)
	at com.google.api.client.googleapis.media.MediaHttpUploader.resumableUpload(MediaHttpUploader.java:417)
	at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:336)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:427)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.pinterest.secor.uploader.GsUploadManager$1.run(GsUploadManager.java:100)
	... 5 more
```

**Comment by slitayem** [comment]
Can anybody please tell us the reason for this error ? 
Thanks.
