### ISSUE TITLE
secor-monitor container not getting started.

### ISSUE THREAD

**Issue by vickykumarmlt** [pinterest/secor#2333]
i have deployed secor in k8s by using docker image from but monitor container is getting failed due to below exception.

docker.io/dawidhaglund/secor/0.29-6

Please help me with that issue. or if we have any docker images that provided by pinterest secor itself please also provide that link as well

2022-08-31 18:41:35,899 [main-EventThread] (org.apache.curator.framework.state.ConnectionStateManager) INFO  State change: CONNECTED
2022-08-31 18:41:35,903 [main] (com.pinterest.secor.main.ProgressMonitorMain) ERROR Progress monitor failed
java.lang.RuntimeException: Failed to find required configuration option 'kafka.client.className'.
	at com.pinterest.secor.common.SecorConfig.checkProperty(SecorConfig.java:725)
	at com.pinterest.secor.common.SecorConfig.getString(SecorConfig.java:731)
	at com.pinterest.secor.common.SecorConfig.getKafkaClientClass(SecorConfig.java:261)
	at com.pinterest.secor.tools.ProgressMonitor.<init>(ProgressMonitor.java:74)
	at com.pinterest.secor.main.ProgressMonitorMain.main(ProgressMonitorMain.java:64)

**Comment by vickykumarmlt** [comment]
help will be appreciated.

**Comment by ambud** [comment]
Do you see the same problem when building from main branch?
