### ISSUE TITLE
Checksum Exception

### ISSUE THREAD

**Issue by RainbowTraveller** [pinterest/secor#234]
Secor works fine for small files on QA and Staging, but prod deployment fails while uploading the file. Hadoop 2.7 libraries are being used.

Following is the error :

Caused by: org.apache.hadoop.fs.ChecksumException: Checksum error: file:/home/mav/secor_prod_binaries_1/message_logs/backup/15166_21/dt=20160725/hour=10/as-i-f0de52a6-error_log-20160725-10-00.gz at 9960448
        at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.readChunk(ChecksumFileSystem.java:254)
        at org.apache.hadoop.fs.FSInputChecker.readChecksumChunk(FSInputChecker.java:276)
        at org.apache.hadoop.fs.FSInputChecker.read1(FSInputChecker.java:228)
        at org.apache.hadoop.fs.FSInputChecker.read(FSInputChecker.java:196)
        at java.io.DataInputStream.read(DataInputStream.java:100)
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:91)
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:59)
        at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:119)
        at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:366)
        at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:338)
        at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1965)
        at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1933)
        at org.apache.hadoop.fs.FileSystem.moveFromLocalFile(FileSystem.java:1920)
        at com.pinterest.secor.util.FileUtil.moveToCloud(FileUtil.java:217)
        at com.pinterest.secor.uploader.HadoopS3UploadManager$1.run(HadoopS3UploadManager.java:68)

It there any way to bypass crc generation and checking ? is it possible that hadoop version has issues ?

More details :
http://stackoverflow.com/questions/38644816/secor-checksum-exception-while-uploading-file

**Comment by RainbowTraveller** [comment]
I tried using S3UploadManager instead Hadoop one. That led to uploading few files. But it fails in the trim() method of Uploader class. Apparently, the FileReader creation also takes codec as a parameter which again brings in Hadoop related libraries and leads to failure. Is there any way to completely bypass usage of Hadoop libraries.  


java.lang.RuntimeException: Failed to apply upload policy
        at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:118)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:106)
Caused by: org.apache.hadoop.fs.ChecksumException: Checksum error: /home/usr/secor_prod_binaries_1/message_logs/backup/21738_20/dt=20160807/hour=02/Hostname-error_log-20160807-02-00.gz at 2096128
        at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.readChunk(ChecksumFileSystem.java:254)
        at org.apache.hadoop.fs.FSInputChecker.readChecksumChunk(FSInputChecker.java:276)
        at org.apache.hadoop.fs.FSInputChecker.read1(FSInputChecker.java:228)
        at org.apache.hadoop.fs.FSInputChecker.read(FSInputChecker.java:196)
        at java.io.DataInputStream.read(DataInputStream.java:149)
        at org.apache.hadoop.io.compress.DecompressorStream.getCompressedData(DecompressorStream.java:159)
        at org.apache.hadoop.io.compress.DecompressorStream.decompress(DecompressorStream.java:143)
        at org.apache.hadoop.io.compress.DecompressorStream.read(DecompressorStream.java:85)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
        at com.pinterest.secor.io.impl.DelimitedTextFileReaderWriterFactory$DelimitedTextFileReader.next(DelimitedTextFileReaderWriterFactory.java:80)
        at com.pinterest.secor.uploader.Uploader.trim(Uploader.java:144)
        at com.pinterest.secor.uploader.Uploader.trimFiles(Uploader.java:177)
        at com.pinterest.secor.uploader.Uploader.checkTopicPartition(Uploader.java:206)
        at com.pinterest.secor.uploader.Uploader.applyPolicy(Uploader.java:216)
        at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:114)

**Comment by HenryCaiHaiying** [comment]
What was the problem of Hadoop libraries?  Does that only for gzip files?

**Comment by RainbowTraveller** [comment]
The Hadoop libraries lead to exception as mentioned in the first part of this question. I did not try for other file format than gzip, as that is the one which is required.

**Comment by RainbowTraveller** [comment]
Another issue using S3UploadManager was failure to compute MD5 sum due to file not found exception. In general the failure I encounter are related to check sum related, which brings down all the independent processes eventually. Is there any special setting/library required for the execution of the same ?

**Comment by RainbowTraveller** [comment]
This vanished when I moved all the secor processes to a single machine instead of distributed set up of secor. Not able to run secor in distributed environment as of now
