### ISSUE TITLE
Secor process stops once-in-a-while

### ISSUE THREAD

**Issue by arvind-kalyan** [pinterest/secor#242]
Hi, 

Found that secor process (seemingly) randomly stops once in a while. This does not happen often, though. There is no information available in the logs too. Any ideas what could be happening?

**Comment by HenryCaiHaiying** [comment]
Do you mean the processed died or just stopped processing the message?

If the process still lives but no longer processing, I suspect Kafka
fetcher thread dies, if you have a more consistently reproducible case, we
can do some thread dump or turn on debug level logging on kafka side to
trace the problem.

If the process died without extra information, that might be out of memory
on native stack, but I doubt that would be the case since secor doesn't use
native library.

**Comment by arvind-kalyan** [comment]
Hi, 

Sorry for the late response.. 
It died without any extra information. Nothing in logs too. 

I took a thread dump of the process before it stopped

I can see a lot of :
"secor-consumer-2_node1_42307_22-leader-finder-thread" #72 prio=5 os_prio=0 tid=0x00007f3490026000 nid=0xa915 waiting on condition [0x00007f35195d8000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000005eb956400> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireInterruptibly(AbstractQueuedSynchronizer.java:897)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1222)
        at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
        at kafka.server.AbstractFetcherThread.partitionCount(AbstractFetcherThread.scala:195)
        at kafka.server.AbstractFetcherManager$$anonfun$shutdownIdleFetcherThreads$2.apply(AbstractFetcherManager.scala:110)
        at kafka.server.AbstractFetcherManager$$anonfun$shutdownIdleFetcherThreads$2.apply(AbstractFetcherManager.scala:109)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)

Can you please help?

What other information should we use to debug?

**Comment by HenryCaiHaiying** [comment]
That thread dump doesn't ring a bell to me.

Is it core dumped or runs out of memory?  It can be running out of native
memory while heap memory is still fine.

If you don't see any core dump files or GC log doesn't show anything
suspicious.  You can monitor the native memory usage by running 'top' to
check the real memory the process is taking.
