### ISSUE TITLE
Finagle thrift null pointer

### ISSUE THREAD

**Issue by castillobgr** [pinterest/secor#250]
Hi!

I'm trying to compile the project running `mvn package`, but I get the following error:

```
[INFO] compiling thrift files [C:\Users\dcastill\dev\secor-0.21\src\main\thrift\secor.thrift] with generators [finagle]
[INFO] copying /thrift/thrift-finagle.null to C:\Users\dcastill\AppData\Local\Temp\thrift-finagle104840994503694103
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.423 s
[INFO] Finished at: 2016-08-26T09:06:01-05:00
[INFO] Final Memory: 16M/487M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.twitter:maven-finagle-thrift-plugin:0.0.9:compile (thrift-sources) on project secor: Execution thrift-sources of goal com.twitter:maven-finagle-thrift-plugin:0.0.9:compile failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.twitter:maven-finagle-thrift-plugin:0.0.9:compile (thrift-sources) on project secor: Execution thrift-sources of goal com.twitter:maven-finagle-thrift-plugin:0.0.9:compile failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution thrift-sources of goal com.twitter:maven-finagle-thrift-plugin:0.0.9:compile failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.NullPointerException
        at org.codehaus.plexus.util.IOUtil.copy(IOUtil.java:188)
        at org.codehaus.plexus.util.IOUtil.copy(IOUtil.java:174)
        at org.codehaus.plexus.util.FileUtils.copyStreamToFile(FileUtils.java:1059)
        at com.twitter.FinagleThriftRunner.getBinary(FinagleThriftRunner.java:53)
        at com.twitter.FinagleThriftRunner.compile(FinagleThriftRunner.java:64)
        at com.twitter.AbstractFinagleThriftMojo.execute(AbstractFinagleThriftMojo.java:191)
        at com.twitter.FinagleThriftCompileMojo.execute(FinagleThriftCompileMojo.java:22)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

It happens on both master and [v0.21](https://github.com/pinterest/secor/releases/tag/v0.21)
Am I missing something? Thanks in advance for your help!

**Comment by HenryCaiHaiying** [comment]
Just tried 'mvn clean package' on a new machine, cannot reproduce your
problem.

Which mvn version are you using?  You can also try 'mvn clean package
-DskipTests' or use '--debug' flag to further debug the problem.

**Comment by castillobg** [comment]
Hi @HenryCaiHaiying! The output I posted originally was the result of running `mvn package -debug`. Sorry for the confusion. Here's my output of `mvn -version`:
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T10:41:47-06:00)
Maven home: C:\Users\dcastill\dev\apache-maven
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_92\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"
```
`mvn clean package -DskipTests` fails with the same error.

**Comment by castillobg** [comment]
On an Amazon Linux instance it compiles just fine off master (after installing `git`, `java-1.8.0-openjdk` and `java-1.8.0-openjdk-devel`).
`mvn -version` output:
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /home/ec2-user/apache-maven-3.3.9
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.24.amzn1.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.11-23.53.amzn1.x86_64", arch: "amd64", family: "unix"
```

Could this be a Windows-specific problem?

**Comment by scboffspring** [comment]
I'm having the same issue on Windows, but I can build the project successfully in CircleCI.
so this looks to be Windows-specific.

**Comment by sleyzerzon** [comment]
I'm reproducing the same error: 

```
[ERROR] Failed to execute goal com.twitter:maven-finagle-thrift-plugin:0.0.9:compile (thrift-sources) on project data-pipeline-secor: Execution thrift-sources of goal com.twitter:maven-finagle-thrift-plugin:0.0.9:compile failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.twitter:maven-finagle-thrift-plugin:0.0.9:compile (thrift-sources) on project data-pipeline-secor: Execution thrift-sources of goal com.twitter:maven-finagle-thrift-plugin:0.0.9:compile failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution thrift-sources of goal com.twitter:maven-finagle-thrift-plugin:0.0.9:compile failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.lang.NullPointerException
        at org.codehaus.plexus.util.IOUtil.copy(IOUtil.java:188)
        at org.codehaus.plexus.util.IOUtil.copy(IOUtil.java:174)
        at org.codehaus.plexus.util.FileUtils.copyStreamToFile(FileUtils.java:1059)
        at com.twitter.FinagleThriftRunner.getBinary(FinagleThriftRunner.java:53)
        at com.twitter.FinagleThriftRunner.compile(FinagleThriftRunner.java:64)
        at com.twitter.AbstractFinagleThriftMojo.execute(AbstractFinagleThriftMojo.java:191)
        at com.twitter.FinagleThriftCompileMojo.execute(FinagleThriftCompileMojo.java:22)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
[ERROR]
```

I think it would be fair to eradicate the problem irrespective of the OS, would vote for reopening the bug.
