### ISSUE TITLE
Unexpected end of input stream

### ISSUE THREAD

**Issue by RainbowTraveller** [pinterest/secor#251]
Again same old story repeats, for small volume and partitions it works. The same set up if used for heavy topic with 60 partitions, it fails. There is not message of regarding processed killed due to insufficient memory etc. This is the message accompanying the checksum error encountered in the issue "Checksum Exception #234". This is thrown by process running on different machine than the one which throws Checksum exception. This is very frustrating and I am not able to use secor in production. Can somebody help what is going wrong here ?

java.lang.RuntimeException: Failed to apply upload policy
        at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:118)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:106)
Caused by: java.io.EOFException: Unexpected end of input stream
        at org.apache.hadoop.io.compress.DecompressorStream.decompress(DecompressorStream.java:145)
        at org.apache.hadoop.io.compress.DecompressorStream.read(DecompressorStream.java:85)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
        at com.pinterest.secor.io.impl.DelimitedTextFileReaderWriterFactory$DelimitedTextFileReader.next(DelimitedTextFileReaderWriterFactory.java:84)
        at com.pinterest.secor.uploader.Uploader.trim(Uploader.java:155)
        at com.pinterest.secor.uploader.Uploader.trimFiles(Uploader.java:189)
        at com.pinterest.secor.uploader.Uploader.checkTopicPartition(Uploader.java:218)
        at com.pinterest.secor.uploader.Uploader.applyPolicy(Uploader.java:228)
        at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:114)

**Comment by RainbowTraveller** [comment]
I moved all secor processes to single machine and this error was gone. Not able to run secor in distributed environment.
