### ISSUE TITLE
NoHttpResponseException

### ISSUE THREAD

**Issue by doriwal** [pinterest/secor#261]
I am using secor secor-0.22-SNAPSHOT.jar

every 20-30 minutes i am getting the following error and process stop 

during the 30 minutes that secor is working , its working very good 

2016-10-06 21:33:15,204 [Thread-8] (com.pinterest.secor.main.ConsumerMain$1:65) ERROR Thread Thread[Thread-8,5,main] failed
java.lang.RuntimeException: Failed to apply upload policy
at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:116)
at com.pinterest.secor.consumer.Consumer.run(Consumer.java:106)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.http.NoHttpResponseException: ia-staging-parquet.s3.amazonaws.com:443 failed to respond
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:188)
at com.pinterest.secor.uploader.FutureHandle.get(FutureHandle.java:34)
at com.pinterest.secor.uploader.Uploader.uploadFiles(Uploader.java:108)
at com.pinterest.secor.uploader.Uploader.checkTopicPartition(Uploader.java:220)
at com.pinterest.secor.uploader.Uploader.applyPolicy(Uploader.java:252)
at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:114)
... 1 more
Caused by: java.lang.RuntimeException: org.apache.http.NoHttpResponseException: ia-staging-parquet.s3.amazonaws.com:443 failed to respond
at com.pinterest.secor.uploader.HadoopS3UploadManager$1.run(HadoopS3UploadManager.java:68)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.NoHttpResponseException: ia-staging-parquet.s3.amazonaws.com:443 failed to respond
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:223)
at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)

**Comment by dangoldin** [comment]
I've seen this a few times when there were some network issues uploading to S3. The nice thing is that secor will retry the upload and only commit the latest offsets to ZooKeeper if the upload succeeds.

**Comment by doriwal** [comment]
Is there a solution ? like config number of retry upload ? can Secor recover from this ? 
What I am currently doing is run secor again till next failure ,  I added watchDog that will start the process in case its down but its not a valid option in production

**Comment by HenryCaiHaiying** [comment]
Will the S3UploadManager works better for you?

**Comment by doriwal** [comment]
Thanks looks like switch from default to S3UploadManager fixed it , its now running for 14 hours , with the default it crashed every hour 

Thanks
