### ISSUE TITLE
GS processing error for Zookeeper

### ISSUE THREAD

**Issue by ahsandar** [pinterest/secor#267]
seems I can connect to `kafka` and get the topic it will read to upload data to `GS`, but what is this error for `zookeeper`, is it related to some config issue  ?
```
 java -ea -Dsecor_group=secor_backup -Dlog4j.configuration=log4j.prod.properties -Dconfig=secor.p
rod.backup.properties -cp secor-0.23-SNAPSHOT.jar:lib/* com.pinterest.secor.main.ConsumerMain
Oct 14, 2016 4:43:12 AM com.twitter.logging.Logger log
INFO: Starting LatchedStatsListener
Oct 14, 2016 4:43:12 AM com.twitter.logging.Logger log
INFO: Admin HTTP interface started on port 9999.
2016-10-14 04:43:17,775 [Thread-5] (kafka.utils.Logging$class:83) WARN  No broker partitions consumed by consumer thread secor_backup_seco
r-staging_18188_14-0 for topic EnigmaProxyStaging
2016-10-14 04:43:17,781 [Thread-9] (kafka.utils.Logging$class:83) WARN  No broker partitions consumed by consumer thread secor_backup_seco
r-staging_18188_18-0 for topic EnigmaProxyStaging
2016-10-14 04:43:18,094 [Thread-7] (kafka.utils.Logging$class:83) WARN  No broker partitions consumed by consumer thread secor_backup_seco
r-staging_18188_16-0 for topic EnigmaProxyStaging
2016-10-14 04:43:18,140 [Thread-8] (kafka.utils.Logging$class:83) WARN  No broker partitions consumed by consumer thread secor_backup_seco
r-staging_18188_17-0 for topic EnigmaProxyStaging
2016-10-14 04:43:18,611 [Thread-4] (kafka.utils.Logging$class:83) WARN  No broker partitions consumed by consumer thread secor_backup_seco
r-staging_18188_13-0 for topic EnigmaProxyStaging
2016-10-14 04:43:18,713 [Thread-6] (kafka.utils.Logging$class:83) WARN  No broker partitions consumed by consumer thread secor_backup_seco
r-staging_18188_15-0 for topic EnigmaProxyStaging
2016-10-14 04:43:20,657 [Thread-7] (com.pinterest.secor.main.ConsumerMain$1:65) ERROR Thread Thread[Thread-7,5,main] failed
java.lang.AssertionError: 1 == 2
        at com.pinterest.secor.common.ZookeeperConnector.getZookeeperAddresses(ZookeeperConnector.java:67)
        at com.pinterest.secor.common.ZookeeperConnector.<init>(ZookeeperConnector.java:57)
        at com.pinterest.secor.uploader.Uploader.init(Uploader.java:63)
        at com.pinterest.secor.consumer.Consumer.init(Consumer.java:75)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:87)
2016-10-14 04:43:20,661 [Thread-5] (com.pinterest.secor.main.ConsumerMain$1:65) ERROR Thread Thread[Thread-5,5,main] failed
java.lang.AssertionError: 1 == 2
        at com.pinterest.secor.common.ZookeeperConnector.getZookeeperAddresses(ZookeeperConnector.java:67)
        at com.pinterest.secor.common.ZookeeperConnector.<init>(ZookeeperConnector.java:57)
        at com.pinterest.secor.uploader.Uploader.init(Uploader.java:63)
        at com.pinterest.secor.consumer.Consumer.init(Consumer.java:75)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:87)
2016-10-14 04:43:20,659 [Thread-8] (com.pinterest.secor.main.ConsumerMain$1:65) ERROR Thread Thread[Thread-8,5,main] failed
java.lang.AssertionError: 1 == 2
        at com.pinterest.secor.common.ZookeeperConnector.getZookeeperAddresses(ZookeeperConnector.java:67)
        at com.pinterest.secor.common.ZookeeperConnector.<init>(ZookeeperConnector.java:57)
        at com.pinterest.secor.uploader.Uploader.init(Uploader.java:63)
        at com.pinterest.secor.consumer.Consumer.init(Consumer.java:75)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:87)
2016-10-14 04:43:20,659 [Thread-3] (com.pinterest.secor.main.ConsumerMain$1:65) ERROR Thread Thread[Thread-3,5,main] failed
java.lang.AssertionError: 1 == 2
        at com.pinterest.secor.common.ZookeeperConnector.getZookeeperAddresses(ZookeeperConnector.java:67)
        at com.pinterest.secor.common.ZookeeperConnector.<init>(ZookeeperConnector.java:57)
        at com.pinterest.secor.uploader.Uploader.init(Uploader.java:63)
        at com.pinterest.secor.consumer.Consumer.init(Consumer.java:75)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:87)
2016-10-14 04:43:20,659 [Thread-6] (com.pinterest.secor.main.ConsumerMain$1:65) ERROR Thread Thread[Thread-6,5,main] failed
java.lang.AssertionError: 1 == 2
        at com.pinterest.secor.common.ZookeeperConnector.getZookeeperAddresses(ZookeeperConnector.java:67)
        at com.pinterest.secor.common.ZookeeperConnector.<init>(ZookeeperConnector.java:57)
        at com.pinterest.secor.uploader.Uploader.init(Uploader.java:63)
        at com.pinterest.secor.consumer.Consumer.init(Consumer.java:75)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:87)
2016-10-14 04:43:20,659 [Thread-9] (com.pinterest.secor.main.ConsumerMain$1:65) ERROR Thread Thread[Thread-9,5,main] failed
java.lang.AssertionError: 1 == 2
        at com.pinterest.secor.common.ZookeeperConnector.getZookeeperAddresses(ZookeeperConnector.java:67)
        at com.pinterest.secor.common.ZookeeperConnector.<init>(ZookeeperConnector.java:57)
        at com.pinterest.secor.uploader.Uploader.init(Uploader.java:63)
        at com.pinterest.secor.consumer.Consumer.init(Consumer.java:75)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:87)
2016-10-14 04:43:20,665 [Thread-4] (com.pinterest.secor.main.ConsumerMain$1:65) ERROR Thread Thread[Thread-4,5,main] failed
java.lang.AssertionError: 1 == 2
        at com.pinterest.secor.common.ZookeeperConnector.getZookeeperAddresses(ZookeeperConnector.java:67)
        at com.pinterest.secor.common.ZookeeperConnector.<init>(ZookeeperConnector.java:57)
        at com.pinterest.secor.uploader.Uploader.init(Uploader.java:63)
        at com.pinterest.secor.consumer.Consumer.init(Consumer.java:75)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:87)
```

**Comment by ahsandar** [comment]
created PR to make the config more clear for users
