### ISSUE TITLE
Build failed - Plugin com.twitter:maven-finagle-thrift-plugin:0.0.9 or one of its dependencies could not be resolved

### ISSUE THREAD

**Issue by jocelyndrean** [pinterest/secor#282]
Hello everyone,
Thanks for your amazing work on this project !
I got an issue when I try to execute mvn package on a fresh project. Do you have any idea on how to fix it ? :/

Thanks in advance for your help :)

```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/apache-maven/apache-maven-3.3.9
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

```
mvn package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.pinterest:secor:jar:0.23-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.codehaus.mojo:exec-maven-plugin @ line 365, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building secor 0.23-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://maven.twttr.com/com/twitter/maven-finagle-thrift-plugin/0.0.9/maven-finagle-thrift-plugin-0.0.9.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:18 min
[INFO] Finished at: 2016-11-02T11:29:59+01:00
[INFO] Final Memory: 11M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin com.twitter:maven-finagle-thrift-plugin:0.0.9 or one of its dependencies could not be resolved: Could not transfer artifact com.twitter:maven-finagle-thrift-plugin:jar:0.0.9 from/to Twitter public Maven repo (http://maven.twttr.com): GET request of: com/twitter/maven-finagle-thrift-plugin/0.0.9/maven-finagle-thrift-plugin-0.0.9.jar from Twitter public Maven repo failed: Premature end of Content-Length delimited message body (expected: 15372312; received: 4568274 -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin com.twitter:maven-finagle-thrift-plugin:0.0.9 or one of its dependencies could not be resolved: Could not transfer artifact com.twitter:maven-finagle-thrift-plugin:jar:0.0.9 from/to Twitter public Maven repo (http://maven.twttr.com): GET request of: com/twitter/maven-finagle-thrift-plugin/0.0.9/maven-finagle-thrift-plugin-0.0.9.jar from Twitter public Maven repo failed
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:128)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor(DefaultMavenPluginManager.java:179)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getMojoDescriptor(DefaultMavenPluginManager.java:284)
	at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor(DefaultBuildPluginManager.java:241)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.setupMojoExecution(DefaultLifecycleExecutionPlanCalculator.java:169)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.setupMojoExecutions(DefaultLifecycleExecutionPlanCalculator.java:155)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:131)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:145)
	at org.apache.maven.lifecycle.internal.builder.BuilderCommon.resolveBuildPlan(BuilderCommon.java:96)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:109)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.twitter:maven-finagle-thrift-plugin:jar:0.0.9 from/to Twitter public Maven repo (http://maven.twttr.com): GET request of: com/twitter/maven-finagle-thrift-plugin/0.0.9/maven-finagle-thrift-plugin-0.0.9.jar from Twitter public Maven repo failed
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:124)
	... 26 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.twitter:maven-finagle-thrift-plugin:jar:0.0.9 from/to Twitter public Maven repo (http://maven.twttr.com): GET request of: com/twitter/maven-finagle-thrift-plugin/0.0.9/maven-finagle-thrift-plugin-0.0.9.jar from Twitter public Maven repo failed
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 30 more
Caused by: org.apache.maven.wagon.TransferFailedException: GET request of: com/twitter/maven-finagle-thrift-plugin/0.0.9/maven-finagle-thrift-plugin-0.0.9.jar from Twitter public Maven repo failed
	at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:363)
	at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:316)
	at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:285)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:97)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	... 35 more
Caused by: org.apache.maven.wagon.providers.http.httpclient.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 15372312; received: 4568274
	at org.apache.maven.wagon.providers.http.httpclient.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:180)
	at org.apache.maven.wagon.providers.http.httpclient.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:531)
	at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:353)
	... 44 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by jocelyndrean** [comment]
Worked on Docker with this image caarlos0/alpine-oraclejdk7-mvn. Do you have a JDK version + Maven version preferences for Secor ?

**Comment by HenryCaiHaiying** [comment]
I think both oraclejdk7 and oraclejdk8 should work, that's how the
travis-ci was setup: https://travis-ci.org/pinterest/secor

**Comment by sleyzerzon** [comment]
Any specific version of Java 8 needs to be used?  We are still seeing the exception with the following config:

$ mvn -v
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T07:57:37-04:00)
Maven home: C:\apache-maven-3.3.3
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: C:\Java\jdk1.8.0_60\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

**Comment by HenryCaiHaiying** [comment]
This is my version:

Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c;
2015-03-13T13:10:27-07:00)

Maven home: /usr/local/Cellar/maven/3.3.1/libexec

Java version: 1.8.0_66, vendor: Oracle Corporation

Java home:
/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre

Default locale: en_US, platform encoding: UTF-8

OS name: "mac os x", version: "10.12.5", arch: "x86_64", family: "mac"

**Comment by csrrmrvll** [comment]
It does not seem like a Maven error, but that the dependency cannot be found in the plugin repository https://maven.twttr.com. The plugin version found there is 0.1.10: https://maven.twttr.com/org/apache/thrift/tools/maven-thrift-plugin/0.1.10/. But any way updating the version does not work either. Any particular entry in maven settings that we are unaware of?

**Comment by HenryCaiHaiying** [comment]
This is related to: https://github.com/pinterest/secor/issues/1051
