### ISSUE TITLE
Getting error 'insufficient data written' when using JsonMessageParser

### ISSUE THREAD

**Issue by ofirsharony** [pinterest/secor#302]
Hi,

I'm sinking my data to Google Cloud Storage. I've suffered from the `insufficient data written` in the past, but managed to bypass it by setting `secor.gs.upload.direct=true`, as suggested in the documentation.

Now, after changing my message parser to `JsonMessageParser`, I get the exception again:
```
java.lang.RuntimeException: Failed to apply upload policy
        at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:116)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:106)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: insufficient data written
```

Any ideas?

**Comment by tygrash** [comment]
If you have solved this issue, then you can close this issue, or if still u need help, you can refer https://github.com/pinterest/secor/issues/232
