### ISSUE TITLE
Configuring secor with multi-node kafka cluster

### ISSUE THREAD

**Issue by pranavoyo** [pinterest/secor#365]
I have 3 node kafka cluster setup in AWS and I am trying to setup secor in it. I am running secor in one of the nodes but it is not working. In /mnt/secor_data,  message_logs dir is not getting created. I have reduced secor.max.file.size.bytes=200000 and secor.max.file.age.seconds=60. I have setup the same in single node cluster and it is working fine as expected. My kafka is version 0.11

Please tell me what values to put in "kafka.seed.broker.host" and "zookeeper.quorum"? I have tried putting both public and private IPs but it is not working. What is the usual guideline to configure secor for multi-node kafka cluster? Please help me with the same.

I am getting these logs on console,

`2017-09-27 07:18:07,324 [ConsumerFetcherThread-secor_backup_ip-172-31-28-189_20031_15-0-3] (kafka.utils.Logging$class:91) WARN  [ConsumerFetcherThread-secor_backup_ip-172-31-28-189_20031_15-0-3], Error in fetch kafka.consumer.ConsumerFetcherThread$FetchRequest@734ee761
java.net.SocketTimeoutException
	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:211)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
	at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:81)
	at kafka.network.BlockingChannel.readCompletely(BlockingChannel.scala:129)
	at kafka.network.BlockingChannel.receive(BlockingChannel.scala:120)
	at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:99)
	at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SimpleConsumer.scala:132)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply$mcV$sp(SimpleConsumer.scala:131)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
	at kafka.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:130)
	at kafka.consumer.ConsumerFetcherThread.fetch(ConsumerFetcherThread.scala:111)
	at kafka.consumer.ConsumerFetcherThread.fetch(ConsumerFetcherThread.scala:31)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:118)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:103)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)`

**Comment by ScottFitz** [comment]
Any update on this? I may be having similar issues.
Thanks.

**Comment by HenryCaiHaiying** [comment]
It seems a configuration error on the broker address.

**Comment by vistorve** [comment]
FWIW I was having the same problem and eventually resolved it by changing the kafka version in the pom.xml to exactly match the version I was running as the server.

I was/am running kafka 0.10.0.1
