### ISSUE TITLE
JsonORCFileReaderWriterFactory crashes for null/non-existing  values

### ISSUE THREAD

**Issue by attilagenc** [pinterest/secor#369]
When you try to use JsonORCFileReaderWriterFactory to generate ORC Files and input message does not contain a value for a column specified in template, secor crashes.

Here is a sample crash and stack trace:

INFO: Cleaning up!
2017-10-13 16:04:54.990 [Thread-3] ERROR (ConsumerMain.java:65) - Thread Thread[Thread-3,5,main] failed
java.lang.RuntimeException: Failed to apply upload policy
	at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:117)
	at com.pinterest.secor.consumer.Consumer.run(Consumer.java:107)
Caused by: java.lang.NullPointerException
	at java.lang.System.arraycopy(Native Method)
	at org.apache.hadoop.io.Text.set(Text.java:225)
	at org.apache.orc.impl.StringRedBlackTree.add(StringRedBlackTree.java:62)
	at org.apache.orc.impl.WriterImpl$StringTreeWriter.writeBatch(WriterImpl.java:1459)
	at org.apache.orc.impl.WriterImpl$StructTreeWriter.writeRootBatch(WriterImpl.java:2098)
	at org.apache.orc.impl.WriterImpl.addRowBatch(WriterImpl.java:2811)
	at com.pinterest.secor.io.impl.JsonORCFileReaderWriterFactory$JsonORCFileWriter.close(JsonORCFileReaderWriterFactory.java:168)
	at com.pinterest.secor.common.FileRegistry.deleteWriter(FileRegistry.java:197)
	at com.pinterest.secor.common.FileRegistry.deleteWriters(FileRegistry.java:218)
	at com.pinterest.secor.common.FileRegistry.deleteWriters(FileRegistry.java:208)
	at com.pinterest.secor.uploader.Uploader.uploadFiles(Uploader.java:104)
	at com.pinterest.secor.uploader.Uploader.checkTopicPartition(Uploader.java:225)
	at com.pinterest.secor.uploader.Uploader.applyPolicy(Uploader.java:257)
	at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:115)
	... 1 more
2017-10-13 16:04:54.990 [Thread-4] ERROR (ConsumerMain.java:65) - Thread Thread[Thread-4,5,main] failed
java.lang.RuntimeException: Failed to apply upload policy
	at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:117)
	at com.pinterest.secor.consumer.Consumer.run(Consumer.java:107)
Caused by: java.lang.NullPointerException
	at java.lang.System.arraycopy(Native Method)
	at org.apache.hadoop.io.Text.set(Text.java:225)
	at org.apache.orc.impl.StringRedBlackTree.add(StringRedBlackTree.java:62)
	at org.apache.orc.impl.WriterImpl$StringTreeWriter.writeBatch(WriterImpl.java:1459)
	at org.apache.orc.impl.WriterImpl$StructTreeWriter.writeRootBatch(WriterImpl.java:2098)
	at org.apache.orc.impl.WriterImpl.addRowBatch(WriterImpl.java:2811)
	at com.pinterest.secor.io.impl.JsonORCFileReaderWriterFactory$JsonORCFileWriter.close(JsonORCFileReaderWriterFactory.java:168)
	at com.pinterest.secor.common.FileRegistry.deleteWriter(FileRegistry.java:197)
	at com.pinterest.secor.common.FileRegistry.deleteWriters(FileRegistry.java:218)
	at com.pinterest.secor.common.FileRegistry.deleteWriters(FileRegistry.java:208)
	at com.pinterest.secor.uploader.Uploader.uploadFiles(Uploader.java:104)
	at com.pinterest.secor.uploader.Uploader.checkTopicPartition(Uploader.java:225)
	at com.pinterest.secor.uploader.Uploader.applyPolicy(Uploader.java:257)
	at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:115)
	... 1 more

**Comment by attilagenc** [comment]
Fix is provide in this(https://github.com/pinterest/secor/pull/370) pull request.

**Comment by attilagenc** [comment]
In my tests batch size was always 1 and my previous fix was to set index value to 0, correct fix should be to use "rowIndex" parameter as index. New  pull request fixes this mistake (https://github.com/pinterest/secor/pull/371)
