### ISSUE TITLE
Secor dies sometimes when an zookeeper box dies.

### ISSUE THREAD

**Issue by orderedchaosdev** [pinterest/secor#405]
Here is one of the errors in which I stopped the zookeeper leader and secor died.
I could start it again after in this case.
```
2018-03-29 21:32:26,935 [Thread-11-EventThread] (org.I0Itec.zkclient.ZkClient:713) INFO  zookeeper state changed (Disconnected)
2018-03-29 21:32:26,935 [Thread-14-EventThread] (org.I0Itec.zkclient.ZkClient:713) INFO  zookeeper state changed (Disconnected)
2018-03-29 21:32:26,936 [Thread-9-EventThread] (org.I0Itec.zkclient.ZkClient:713) INFO  zookeeper state changed (Disconnected)
2018-03-29 21:32:26,936 [Thread-8-EventThread] (org.I0Itec.zkclient.ZkClient:713) INFO  zookeeper state changed (Disconnected)
2018-03-29 21:32:26,937 [Thread-12-EventThread] (org.I0Itec.zkclient.ZkClient:713) INFO  zookeeper state changed (Disconnected)
2018-03-29 21:32:26,937 [Thread-10-EventThread] (org.I0Itec.zkclient.ZkClient:713) INFO  zookeeper state changed (Disconnected)
2018-03-29 21:32:26,936 [Thread-8] (com.pinterest.secor.main.ConsumerMain$1:65) ERROR Thread Thread[Thread-8,5,main] failed
java.lang.RuntimeException: Failed to apply upload policy
	at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:117)
	at com.pinterest.secor.consumer.Consumer.run(Consumer.java:107)
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /kafka_dev/consumers/secor_dev/offsets/transaction/11
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1184)
	at com.pinterest.secor.common.ZookeeperConnector.getCommittedOffsetCount(ZookeeperConnector.java:116)
	at com.pinterest.secor.uploader.Uploader.checkTopicPartition(Uploader.java:220)
	at com.pinterest.secor.uploader.Uploader.applyPolicy(Uploader.java:258)
	at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:115)
	... 1 more
2018-03-29 21:32:26,937 [Thread-17-EventThread] (org.I0Itec.zkclient.ZkClient:713) INFO  zookeeper state changed (Disconnected)
2018-03-29 21:32:26,940 [Thread-6-EventThread] (org.I0Itec.zkclient.ZkClient:713) INFO  zookeeper state changed (Disconnected)```

**Comment by HenryCaiHaiying** [comment]
By looking at the code in ZookeeperConnector.getCommittedOffsetCount, we didn't catch or retry on that Exception.  If you want, you can modify that portion of the code a little to add some retries, it probably will make the secor more resilient on that type of connection issue.
