### ISSUE TITLE
Consumer Rebalancing Fails

### ISSUE THREAD

**Issue by SMR39** [pinterest/secor#418]
HI,

I am experiencing issues while initializing consumer. _I set ZOOKEEPER_PATH = /_

```2018-05-24 21:23:00,977 [Thread-3] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_14], end registering consumer evok_secor-6b59876bc4-dj8gq_7_14 in ZK
2018-05-24 21:23:00,977 [Thread-6] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_17], end registering consumer evok_secor-6b59876bc4-dj8gq_7_17 in ZK
2018-05-24 21:23:00,977 [Thread-9] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_20], end registering consumer evok_secor-6b59876bc4-dj8gq_7_20 in ZK
2018-05-24 21:23:00,977 [Thread-4] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_15], end registering consumer evok_secor-6b59876bc4-dj8gq_7_15 in ZK
2018-05-24 21:23:00,977 [Thread-5] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_16], end registering consumer evok_secor-6b59876bc4-dj8gq_7_16 in ZK
2018-05-24 21:23:00,979 [Thread-8] (kafka.utils.ZKCheckedEphemeral) INFO  Result of znode creation is: OK
2018-05-24 21:23:00,979 [Thread-8] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_19], end registering consumer evok_secor-6b59876bc4-dj8gq_7_19 in ZK
2018-05-24 21:23:00,981 [evok_secor-6b59876bc4-dj8gq_7_18_watcher_executor] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_18], starting watcher executor thread for consumer evok_secor-6b59876bc4-dj8gq_7_18
2018-05-24 21:23:00,981 [evok_secor-6b59876bc4-dj8gq_7_17_watcher_executor] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_17], starting watcher executor thread for consumer evok_secor-6b59876bc4-dj8gq_7_17
2018-05-24 21:23:00,981 [evok_secor-6b59876bc4-dj8gq_7_20_watcher_executor] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_20], starting watcher executor thread for consumer evok_secor-6b59876bc4-dj8gq_7_20
2018-05-24 21:23:00,983 [evok_secor-6b59876bc4-dj8gq_7_14_watcher_executor] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_14], starting watcher executor thread for consumer evok_secor-6b59876bc4-dj8gq_7_14
2018-05-24 21:23:00,983 [evok_secor-6b59876bc4-dj8gq_7_19_watcher_executor] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_19], starting watcher executor thread for consumer evok_secor-6b59876bc4-dj8gq_7_19
2018-05-24 21:23:00,983 [evok_secor-6b59876bc4-dj8gq_7_16_watcher_executor] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_16], starting watcher executor thread for consumer evok_secor-6b59876bc4-dj8gq_7_16
2018-05-24 21:23:00,983 [evok_secor-6b59876bc4-dj8gq_7_15_watcher_executor] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_15], starting watcher executor thread for consumer evok_secor-6b59876bc4-dj8gq_7_15
2018-05-24 21:23:01,002 [Thread-9] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_20], begin rebalancing consumer evok_secor-6b59876bc4-dj8gq_7_20 try #0
2018-05-24 21:23:01,002 [Thread-7] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_18], begin rebalancing consumer evok_secor-6b59876bc4-dj8gq_7_18 try #0
2018-05-24 21:23:01,002 [Thread-5] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_16], begin rebalancing consumer evok_secor-6b59876bc4-dj8gq_7_16 try #0
2018-05-24 21:23:01,002 [Thread-3] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_14], begin rebalancing consumer evok_secor-6b59876bc4-dj8gq_7_14 try #0
2018-05-24 21:23:01,002 [Thread-8] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_19], begin rebalancing consumer evok_secor-6b59876bc4-dj8gq_7_19 try #0
2018-05-24 21:23:01,002 [Thread-6] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_17], begin rebalancing consumer evok_secor-6b59876bc4-dj8gq_7_17 try #0
2018-05-24 21:23:01,002 [Thread-4] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_15], begin rebalancing consumer evok_secor-6b59876bc4-dj8gq_7_15 try #0
2018-05-24 21:23:01,075 [Thread-3] (kafka.consumer.ZookeeperConsumerConnector) INFO  [evok_secor-6b59876bc4-dj8gq_7_14], exception during rebalance 
kafka.common.KafkaException: Failed to parse the broker info from zookeeper: {"listener_security_protocol_map":{"OUTSIDE":"PLAINTEXT","PLAINTEXT":"PLAINTEXT"},"endpoints":["OUTSIDE://blah:32400","PLAINTEXT://blah:9092"],"rack":"us-west-2a","jmx_port":5555,"host":"blah","timestamp":"1526933733069","port":32400,"version":4}
	at kafka.cluster.Broker$.createBroker(Broker.scala:101)
	at kafka.utils.ZkUtils$$anonfun$getCluster$1.apply(ZkUtils.scala:587)
	at kafka.utils.ZkUtils$$anonfun$getCluster$1.apply(ZkUtils.scala:585)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1156)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at kafka.utils.ZkUtils.getCluster(ZkUtils.scala:585)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$syncedRebalance$1$$anonfun$apply$mcV$sp$1.apply$mcVI$sp(ZookeeperConsumerConnector.scala:645)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:142)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$syncedRebalance$1.apply$mcV$sp(ZookeeperConsumerConnector.scala:637)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$syncedRebalance$1.apply(ZookeeperConsumerConnector.scala:637)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$syncedRebalance$1.apply(ZookeeperConsumerConnector.scala:637)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener.syncedRebalance(ZookeeperConsumerConnector.scala:636)
	at kafka.consumer.ZookeeperConsumerConnector.kafka$consumer$ZookeeperConsumerConnector$$reinitializeConsumer(ZookeeperConsumerConnector.scala:977)
	at kafka.consumer.ZookeeperConsumerConnector$WildcardStreamsHandler.&lt;init&gt;(ZookeeperConsumerConnector.scala:1011)
	at kafka.consumer.ZookeeperConsumerConnector.createMessageStreamsByFilter(ZookeeperConsumerConnector.scala:173)
	at kafka.javaapi.consumer.ZookeeperConsumerConnector.createMessageStreamsByFilter(ZookeeperConsumerConnector.scala:101)
	at kafka.javaapi.consumer.ZookeeperConsumerConnector.createMessageStreamsByFilter(ZookeeperConsumerConnector.scala:108)
	at com.pinterest.secor.reader.MessageReader.&lt;init&gt;(MessageReader.java:78)
	at com.pinterest.secor.consumer.Consumer.init(Consumer.java:69)
	at com.pinterest.secor.consumer.Consumer.run(Consumer.java:88)
Caused by: java.lang.IllegalArgumentException: No enum constant org.apache.kafka.common.protocol.SecurityProtocol.OUTSIDE
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.apache.kafka.common.protocol.SecurityProtocol.valueOf(SecurityProtocol.java:28)
```

I would really appreciate if some one can help me understand whats going on.  I find on the internet sometime it is kafka version that is incomaptible. I run kafka 1.0.1

best,
shashi

**Comment by HenryCaiHaiying** [comment]
Is the kafka version in secor's pom.xml 1.0.1 or 0.10.2?

**Comment by SMR39** [comment]
in the pom there are three profiles 
kafka-0.10.0.1
kafka-0.10-dev
kafka-0.10.2.0

My version is 2.11-1.0.1

So I guess my version is not compatible. Adding a new profile helps?

**Comment by SMR39** [comment]
I went ahead and tried to package with updated pom.xml 
 mvn -Pkafka-1.0.1 package


```pom.xml 
========
  <profile>
            <id>kafka-1.0.1</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>org.apache.kafka</groupId>
                    <artifactId>kafka_2.11</artifactId>
                    <version>1.0.1</version>
                    <exclusions>
                        <exclusion>
                            <groupId>org.slf4j</groupId>
                            <artifactId>slf4j-simple</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
            </dependencies>
        </profile>```

```Results :

Tests in error:
  testExtractTimestampMillis(com.pinterest.secor.parser.MessagePackParserTest): com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V
  testExtractTimestampMillisFromKafkaTimestamp(com.pinterest.secor.parser.MessagePackParserTest): com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V
  testExtractPartitions(com.pinterest.secor.parser.MessagePackParserTest): com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V
  testMissingTimestamp(com.pinterest.secor.parser.MessagePackParserTest): com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V
  testUnsupportedTimestampFormat(com.pinterest.secor.parser.MessagePackParserTest): com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V
  testNullTimestamp(com.pinterest.secor.parser.MessagePackParserTest): com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V```

**Comment by HenryCaiHaiying** [comment]
com.fasterxml.jackson.core.JsonGenerator might need to move up as well.

**Comment by SMR39** [comment]
Thanks for your help that worked .. Will let you know if that solved the original issue.

**Comment by SMR39** [comment]
I have also upgraded ostrich to 2.11 since scala version was a mismatch too
But now I get 

```java.lang.NoSuchMethodError: scala.collection.immutable.List.fromArray(Ljava/lang/Object;)Lscala/collection/immutable/List;
	at com.pinterest.secor.common.OstrichAdminService.start(OstrichAdminService.java:56)
	at com.pinterest.secor.main.ConsumerMain.main(ConsumerMain.java:56)```

**Comment by clintfred** [comment]
@SMR39 Would you mind sharing your entries for com.fasterxml.jackson.core.JsonGenerator and ostrich?

**Comment by norrs** [comment]
@SMR39 @HenryCaiHaiying @clintfred : Fixes are here: https://github.com/pinterest/secor/pull/421 . But I couldn't keep the default activated profile, as maven then mixed scala versions inclusions between 2.10 and 2.11 :-/

**Comment by HenryCaiHaiying** [comment]
left a comment in #421
