### ISSUE TITLE
Having issues connecting to SoftLayer Object Store, Swift or S3

### ISSUE THREAD

**Issue by cameronbraid** [pinterest/secor#453]
Hi,

I am trying to evaluate secor for backing up kafka topics within IBM softlayer, and have tried both the cloud.service=S3 and cloud.service=Swift and havnt had success with either.

First of all with Swift, I set the following props

```
cloud.service=Swift

swift.use.get.auth=true
# auth url provided from control.softlayer.com, and on https://knowledgelayer.softlayer.com/faq/what-are-object-storage-authentication-endpoints-public-and-private-networks
swift.auth.url=https://mel01.objectstorage.softlayer.net/auth/v1.0
swift.tenant=
swift.username=MY_USERNAME
swift.port=
swift.public=true
swift.region=
swift.prefix=
swift.password=
swift.api.key=MY_KEY
```

And I get the following error 

```
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Authentication Failure: Auth as tenant '' user 'MY_USER' with key of length 64  POST https://mel01.objectstorage.softlayer.net/auth/v1.0 => 400 : <html><h1>Bad Request</h1><p>The server could not comply with the request since it is either malformed or otherwise incorrect.</p></html>
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.pinterest.secor.uploader.FutureHandle.get(FutureHandle.java:34)
	at com.pinterest.secor.uploader.Uploader.uploadFiles(Uploader.java:126)
	at com.pinterest.secor.uploader.Uploader.checkTopicPartition(Uploader.java:245)
	at com.pinterest.secor.uploader.Uploader.applyPolicy(Uploader.java:277)
	at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:115)
Caused by: java.lang.RuntimeException: Authentication Failure: Auth as tenant '' user 'MY_USER' with key of length 64  POST https://mel01.objectstorage.softlayer.net/auth/v1.0 => 400 : <html><h1>Bad Request</h1><p>The server could not comply with the request since it is either malformed or otherwise incorrect.</p></html>
	at com.pinterest.secor.uploader.HadoopS3UploadManager$1.run(HadoopS3UploadManager.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Authentication Failure: Auth as tenant '' user 'MY_USER' with key of length 64  POST https://mel01.objectstorage.softlayer.net/auth/v1.0 => 400 : <html><h1>Bad Request</h1><p>The server could not comply with the request since it is either malformed or otherwise incorrect.</p></html>
	at org.apache.hadoop.fs.swift.http.SwiftRestClient$AuthenticationPost.extractResult(SwiftRestClient.java:1123)
	at org.apache.hadoop.fs.swift.http.SwiftRestClient$AuthenticationPost.extractResult(SwiftRestClient.java:1084)
	at org.apache.hadoop.fs.swift.http.SwiftRestClient.perform(SwiftRestClient.java:1406)
	at org.apache.hadoop.fs.swift.http.SwiftRestClient.authenticate(SwiftRestClient.java:1079)
	at org.apache.hadoop.fs.swift.http.SwiftRestClient.authIfNeeded(SwiftRestClient.java:1298)
	at org.apache.hadoop.fs.swift.http.SwiftRestClient.preRemoteCommand(SwiftRestClient.java:1314)
	at org.apache.hadoop.fs.swift.http.SwiftRestClient.headRequest(SwiftRestClient.java:1015)
	at org.apache.hadoop.fs.swift.snative.SwiftNativeFileSystemStore.stat(SwiftNativeFileSystemStore.java:258)
	at org.apache.hadoop.fs.swift.snative.SwiftNativeFileSystemStore.getObjectMetadata(SwiftNativeFileSystemStore.java:213)
	at org.apache.hadoop.fs.swift.snative.SwiftNativeFileSystemStore.getObjectMetadata(SwiftNativeFileSystemStore.java:182)
	at org.apache.hadoop.fs.swift.snative.SwiftNativeFileSystem.getFileStatus(SwiftNativeFileSystem.java:173)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1424)
	at org.apache.hadoop.fs.FileUtil.checkDest(FileUtil.java:496)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:348)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:338)
	at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1965)
	at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1933)
	at org.apache.hadoop.fs.FileSystem.moveFromLocalFile(FileSystem.java:1920)
	at com.pinterest.secor.util.FileUtil.moveToCloud(FileUtil.java:208)
	at com.pinterest.secor.uploader.HadoopS3UploadManager$1.run(HadoopS3UploadManager.java:66)

```

One thing that strikes me as odd, but may well be intended, is the use of .pinterest.secor.uploader.HadoopS3UploadManager . I can see in the source there are different upload managers for Azure, GC, however I think that maybe correct since it is using hadoop's filesystem abstraction to write to swift. 

Any pointers on getting this connected ?

**Comment by HenryCaiHaiying** [comment]
I am not sure how many people are familiar with swift.  By looking at the
checkin history of README.md, look slike Guy Hadash added openstack swift
in 2015, maybe you can ping him ...?
