### ISSUE TITLE
No brokers found when trying to rebalance

### ISSUE THREAD

**Issue by jarkko-turpeinen** [pinterest/secor#457]
I try to connect IBM Cloud Message Hub. It does not expose its zookeeper (not allowed to connect). Is there a way secor to connect to Kafka brokers directly?

`INFO: Admin HTTP interface started on port 9999.
2018-09-17 10:54:02,784 [Thread-7] (kafka.utils.Logging$class:85) WARN  [secor_backup_ubuntu_4099_16], no brokers found when trying to rebalance.
2018-09-17 10:54:02,994 [Thread-3] (com.pinterest.secor.main.ConsumerMain$1:65) ERROR Thread Thread[Thread-3,5,main] failed
java.lang.AssertionError: 1 == 2
	at com.pinterest.secor.common.ZookeeperConnector.getZookeeperAddresses(ZookeeperConnector.java:67)
	at com.pinterest.secor.common.ZookeeperConnector.<init>(ZookeeperConnector.java:57)
	at com.pinterest.secor.uploader.Uploader.init(Uploader.java:77)
	at com.pinterest.secor.consumer.Consumer.init(Consumer.java:76)
	at com.pinterest.secor.consumer.Consumer.run(Consumer.java:88)
`

**Comment by HenryCaiHaiying** [comment]
secor needs to save the offsets in ZK and also use ZK for locking purpose, unless you modify that portion of the code, you would have that ZK dependency.
