### ISSUE TITLE
ERROR Partition finalizer failed

### ISSUE THREAD

**Issue by itsmesrds** [pinterest/secor#560]
When i run the Secor this is Coming in Secor finalizer logs:

2019-02-13 21:42:01,871 [main-SendThread(kafka0:2181)] (org.apache.zookeeper.ClientCnxn$SendThread:818) DEBUG Reading reply sessionid:0x168e6155cd9079c, packet:: clientPath:null serverPath:null finished:false header:: 1,8  replyHeader:: 1,4294976595,-101  request:: '/consumers/secor-orc6/offsets,F  response:: v{}
2019-02-13 21:42:01,871 [main-SendThread(kafka2:2181)] (org.apache.zookeeper.ClientCnxn$SendThread:818) DEBUG Reading reply sessionid:0x368e6155e6902a1, packet:: clientPath:null serverPath:null finished:false header:: 1,8  replyHeader:: 1,4294976595,-101  request:: '/consumers/secor-orc6/offsets,F  response:: v{}
2019-02-13 21:42:01,878 [main] (com.pinterest.secor.main.PartitionFinalizerMain:47) ERROR Partition finalizer failed
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /consumers/secor-orc6/offsets
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1472)
        at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1500)
        at com.pinterest.secor.common.ZookeeperConnector.getCommittedOffsetTopics(ZookeeperConnector.java:140)

What could be the Problem in this ?

**Comment by HenryCaiHaiying** [comment]
The error is indicating this ZK node: /consumers/secor-orc6/offsets doesn't exist, do you have another error early on?  I think secor should already created this ZK node prior.
