### ISSUE TITLE
ProgressMonitor keeps exiting with `java.nio.channels.ClosedChannelException`

### ISSUE THREAD

**Issue by nikshepsvn** [pinterest/secor#601]
I've used supervisord to launch both Secor and the ProgressMonitor tool together, secor runs fine but the ProgressMonitor tool aways fails with this error 

```
2019-03-01 00:29:35,119 [main] (kafka.consumer.SimpleConsumer) INFO  Reconnect due to error:
java.nio.channels.ClosedChannelException
	at kafka.network.BlockingChannel.send(BlockingChannel.scala:110)
	at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:85)
	at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83)
	at kafka.consumer.SimpleConsumer.send(SimpleConsumer.scala:111)
	at kafka.javaapi.consumer.SimpleConsumer.send(SimpleConsumer.scala:68)
	at com.pinterest.secor.common.LegacyKafkaClient.findLeader(LegacyKafkaClient.java:76)
	at com.pinterest.secor.common.LegacyKafkaClient.createConsumer(LegacyKafkaClient.java:168)
	at com.pinterest.secor.common.LegacyKafkaClient.getCommittedMessage(LegacyKafkaClient.java:231)
	at com.pinterest.secor.tools.ProgressMonitor.getStats(ProgressMonitor.java:207)
	at com.pinterest.secor.tools.ProgressMonitor.exportStats(ProgressMonitor.java:143)
	at com.pinterest.secor.main.ProgressMonitorMain.main(ProgressMonitorMain.java:70)
```

Any recommendation on what to look at/is causing the problem would be appreciated.

**Comment by HenryCaiHaiying** [comment]
Which kafka version are you using?  The simple consumer might no longer
work in that version.

**Comment by nikshepsvn** [comment]
We're using Kafka 1.1.1, I changed the LegacyKafkaConsumer to SecorKafkaConsumer in an attempt to fix stuff but then I get an error saying that java cannot find the `SecorKafkaConsumer` -- I'm guessing this is due to the fact SecorKafkaConsumer is not in the classpath. Can you help me modify the pom.xml file to not include the SecorKafkaConsumer and SecorKafkaMessageIterator?
