### ISSUE TITLE
Guava upgrade causes RateLimitUtil.acquire error

### ISSUE THREAD

**Issue by rylanhalteman** [pinterest/secor#89]
I tried running 9937d7d9c78281b756b620e8cd2a353bb8420cdc, and it fails with the following stack trace.

```
May 04, 2015 8:11:43 PM com.twitter.logging.Logger log
INFO: Starting LatchedStatsListener
May 04, 2015 8:11:43 PM com.twitter.logging.Logger log
INFO: Admin HTTP interface started on port 9990.
2015-05-04 20:11:45,862 [Thread-4] (kafka.utils.Logging$class:83) WARN  [secor_mobile_ip-X_26621_13], No broker partitions consumed by consumer thread secor_mobile_ip-X_26621_13-0 for topic mobile
2015-05-04 20:11:45,864 [Thread-5] (kafka.utils.Logging$class:83) WARN  [secor_mobile_ip-X_26621_14], No broker partitions consumed by consumer thread secor_mobile_ip-X_26621_14-0 for topic mobile
2015-05-04 20:11:45,873 [Thread-7] (kafka.utils.Logging$class:83) WARN  [secor_mobile_ip-X_26621_16], No broker partitions consumed by consumer thread secor_mobile_ip-X_26621_16-0 for topic mobile
2015-05-04 20:11:45,877 [Thread-3] (kafka.utils.Logging$class:83) WARN  [secor_mobile_ip-X_26621_12], No broker partitions consumed by consumer thread secor_mobile_ip-X_26621_12-0 for topic mobile
2015-05-04 20:11:45,888 [Thread-6] (kafka.utils.Logging$class:83) WARN  [secor_mobile_ip-X_26621_15], No broker partitions consumed by consumer thread secor_mobile_ip-X_26621_15-0 for topic mobile
2015-05-04 20:11:46,912 [secor_mobile_ip-X_26621_14_watcher_executor] (kafka.utils.Logging$class:83) WARN  [secor_mobile_ip-X_26621_14], No broker partitions consumed by consumer thread secor_mobile_ip-X_26621_14-0 for topic mobile
2015-05-04 20:11:46,921 [secor_mobile_ip-X_26621_15_watcher_executor] (kafka.utils.Logging$class:83) WARN  [secor_mobile_ip-X_26621_15], No broker partitions consumed by consumer thread secor_mobile_ip-X_26621_15-0 for topic mobile
2015-05-04 20:11:46,928 [secor_mobile_ip-X_26621_16_watcher_executor] (kafka.utils.Logging$class:83) WARN  [secor_mobile_ip-X_26621_16], No broker partitions consumed by consumer thread secor_mobile_ip-X_26621_16-0 for topic mobile
2015-05-04 20:11:47,143 [Thread-3] (com.pinterest.secor.main.ConsumerMain$1:65) ERROR Thread Thread[Thread-3,5,main] failed
java.lang.NoSuchMethodError: com.google.common.util.concurrent.RateLimiter.acquire()D
        at com.pinterest.secor.util.RateLimitUtil.acquire(RateLimitUtil.java:39)
        at com.pinterest.secor.reader.MessageReader.read(MessageReader.java:144)
        at com.pinterest.secor.consumer.Consumer.consumeNextMessage(Consumer.java:121)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:90)
```

Reverting to ac688f5f7a4ef054a580c2abd755feadd5f42aa7 fixes the issue.  I am running OpenJDK 1.7.0_65

```
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
```

**Comment by zackdever** [comment]
I'm getting the same error. Reverting deb83deaad76d4c289bb05f3e9d7fc5d7d5be164 fixed it. I don't know what the root cause is. Is moving Guava back to 14.0 an option? @mulloymorrow any thoughts?
