### ISSUE TITLE
ORC reader/writer causes NoClassDefFoundError: HdfsDataOutputStream$SyncFlag

### ISSUE THREAD

**Issue by suminb** [pinterest/secor#943]
I'm trying to store the data on S3 in ORC format by setting `secor.file.reader.writer.factory` as follows:

```
secor.file.reader.writer.factory=com.pinterest.secor.io.impl.JsonORCFileReaderWriterFactory
```

It works without issues when the reader/writer (`SequenceFileReaderWriterFactory`) is used, but it appears `JsonORCFileReaderWriterFactory` causes a `NoClassDefFoundError` exception, stating that `HdfsDataOutputStream$SyncFlag` class is not found.

I'm suspecting it's because the latest version of secor (6f51fcd) relies on `hadoop-common:2.7.0` which is missing `HdfsDataOutputStream$SyncFlag`. However, it looks like a [more recent version of `hadoop-common` comes with the `HdfsDataOutputStream$SyncFlag` class](https://hadoop.apache.org/docs/r2.9.2/hadoop-project-dist/hadoop-hdfs-client/api/org/apache/hadoop/hdfs/client/HdfsDataOutputStream.SyncFlag.html).

Anyway, here's a part of the stack trace:

```
java.lang.NoClassDefFoundError: org/apache/hadoop/hdfs/client/HdfsDataOutputStream$SyncFlag
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.orc.impl.HadoopShimsFactory.createShimByName(HadoopShimsFactory.java:39)
        at org.apache.orc.impl.HadoopShimsFactory.get(HadoopShimsFactory.java:62)
        at org.apache.orc.OrcFile$WriterOptions.<init>(OrcFile.java:477)
        at org.apache.orc.OrcFile.writerOptions(OrcFile.java:930)
        at com.pinterest.secor.io.impl.JsonORCFileReaderWriterFactory$JsonORCFileWriter.<init>(JsonORCFileReaderWriterFactory.java:162)
        at com.pinterest.secor.io.impl.JsonORCFileReaderWriterFactory.BuildFileWriter(JsonORCFileReaderWriterFactory.java:83)
        at com.pinterest.secor.util.ReflectionUtil.createFileWriter(ReflectionUtil.java:156)
        at com.pinterest.secor.common.FileRegistry.getOrCreateWriter(FileRegistry.java:135)
        at com.pinterest.secor.writer.MessageWriter.write(MessageWriter.java:103)
        at com.pinterest.secor.consumer.Consumer.consumeNextMessage(Consumer.java:230)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:148)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hdfs.client.HdfsDataOutputStream$SyncFlag
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 13 more
```

The command I used is:

```
java -ea \
    -Dsecor_group=secor_backup \
    -Dlog4j.configuration=log4j.prod.properties \
    -Dconfig=secor.prod.backup.properties \
    -cp secor-0.28-SNAPSHOT.jar:lib/* \
     com.pinterest.secor.main.ConsumerMain
```

**Comment by suminb** [comment]
Figured it out. It was because `pom.xml` was pointing `hadoop-common:2.7.0`, so I tried it with a newer version. `hadoop-common:3.1.0` works without issues.
