### ISSUE TITLE
Unhandled type map<string,string>

### ISSUE THREAD

**Issue by suminb** [pinterest/secor#972]
It appears `VectorColumnFiller.JsonConverter` is unable to handle `map` types.

```
Caused by: java.lang.IllegalArgumentException: Unhandled type map<string,string>
        at com.pinterest.secor.util.orc.VectorColumnFiller.createConverter(VectorColumnFiller.java:246)
        at com.pinterest.secor.io.impl.JsonORCFileReaderWriterFactory$JsonORCFileWriter.<init>(JsonORCFileReaderWriterFactory.java:158)
        at com.pinterest.secor.io.impl.JsonORCFileReaderWriterFactory.BuildFileWriter(JsonORCFileReaderWriterFactory.java:83)
        at com.pinterest.secor.util.ReflectionUtil.createFileWriter(ReflectionUtil.java:156)
        at com.pinterest.secor.common.FileRegistry.getOrCreateWriter(FileRegistry.java:135)
        at com.pinterest.secor.writer.MessageWriter.write(MessageWriter.java:103)
        at com.pinterest.secor.consumer.Consumer.consumeNextMessage(Consumer.java:230)
        ... 1 more
```

`JsonConverter` doesn't seem to handle `map` types indeed, but `TypeDescription.Category` defines `MAP` which leads me to believe that it was originally planned to support the type. Is there any reason for this, or is it because this project is still under development?

```
    public static JsonConverter createConverter(TypeDescription schema) {
        switch (schema.getCategory()) {
        case BYTE:
        case SHORT:
        case INT:
        case LONG:
            return new LongColumnConverter();
        case FLOAT:
        case DOUBLE:
            return new DoubleColumnConverter();
        case CHAR:
        case VARCHAR:
        case STRING:
            return new StringColumnConverter();
        case DECIMAL:
            return new DecimalColumnConverter();
        case TIMESTAMP:
            return new TimestampColumnConverter();
        case BINARY:
            return new BinaryColumnConverter();
        case BOOLEAN:
            return new BooleanColumnConverter();
        case STRUCT:
            return new StructColumnConverter(schema);
        case LIST:
            return new ListColumnConverter(schema);
        default:
            throw new IllegalArgumentException("Unhandled type " + schema);
        }
    }
```

**Comment by HenryCaiHaiying** [comment]
Please feel free to submit a PR to fix that issue.

**Comment by suminb** [comment]
#982 resolves this.
