### ISSUE TITLE
Potential file corruption when storing in ORC format

### ISSUE THREAD

**Issue by suminb** [pinterest/secor#999]
I'm trying to load data from Kafka to S3 in ORC format. It mostly works okay but occasionally crashes with the following trace. When I try to locate the `1_13_00000000000102544584` file for further investigation, it no longer exists.

Does anyone have any idea on how to pinpoint what the root cause is?

```
2019-10-10 18:02:15,531 [Thread-9] (com.pinterest.secor.consumer.Consumer:172) ERROR Thread failed
java.lang.RuntimeException: Failed to apply upload policy
        at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:182)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:163)
Caused by: java.io.IOException: Problem reading file footer /mnt/secor_data/message_logs/backup_local/12969_22/${topic}/offset=102000000/1_13_00000000000102544584
        at org.apache.orc.impl.ReaderImpl.extractFileTail(ReaderImpl.java:716)
        at org.apache.orc.impl.ReaderImpl.<init>(ReaderImpl.java:500)
        at org.apache.orc.OrcFile.createReader(OrcFile.java:365)
        at com.pinterest.secor.io.impl.JsonORCFileReaderWriterFactory$JsonORCFileReader.<init>(JsonORCFileReaderWriterFactory.java:100)
        at com.pinterest.secor.io.impl.JsonORCFileReaderWriterFactory.BuildFileReader(JsonORCFileReaderWriterFactory.java:77)
        at com.pinterest.secor.util.ReflectionUtil.createFileReader(ReflectionUtil.java:173)
        at com.pinterest.secor.uploader.Uploader.createReader(Uploader.java:163)
        at com.pinterest.secor.uploader.Uploader.trim(Uploader.java:192)
        at com.pinterest.secor.uploader.Uploader.trimFiles(Uploader.java:238)
        at com.pinterest.secor.uploader.Uploader.checkTopicPartition(Uploader.java:297)
        at com.pinterest.secor.uploader.Uploader.applyPolicy(Uploader.java:320)
        at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:180)
        ... 1 more
Caused by: java.lang.IllegalArgumentException
        at java.nio.Buffer.position(Buffer.java:244)
        at org.apache.orc.impl.InStream$UncompressedStream.setCurrent(InStream.java:134)
        at org.apache.orc.impl.InStream$UncompressedStream.reset(InStream.java:110)
        at org.apache.orc.impl.InStream$UncompressedStream.<init>(InStream.java:100)
        at org.apache.orc.impl.InStream.create(InStream.java:837)
        at org.apache.orc.impl.ReaderImpl.extractFileTail(ReaderImpl.java:706)
        ... 12 more
```

**Comment by HenryCaiHaiying** [comment]
We don't have in-house expertise on ORC files
